<link rel="stylesheet" href="css/contato.css">
<div class="container mt-4" id="contato">
    <div class="row d-flex justify-content-start">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h3 class="text-center mb-5" id="contato-titulo">Contato</h3>
    <div class="container" id="cards">
        <div class="row gy-4">
            <div class="col-sm-4 col-6">
                <a href="https://api.whatsapp.com/send?phone=5598984254650">
                    <div class="card">
                        <i class="fa-brands fa-whatsapp whatsapp-icon"></i>
                        <h6 class="mt-2">WhatsApp</h6>
                    </div>
                </a>
            </div>
            <div class="col-sm-4 col-6">
                <a href="/mensagem">
                    <div class="card">
                        <i class="fa-solid fa-envelope email-icon"></i>
                        <h6 class="mt-2">Enviar Mensagem</h6>
                    </div>
                </a>
            </div>
            <div class="col-sm-4 col-6">
                <a href="/inscricao">
                    <div class="card">
                        <i class="fa-solid fa-calendar-check calendar-icon"></i>
                        <h6 class="mt-2">Pré-Matrícula</h6>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<script src="js/contato.js"></script>
    