<?php
require 'php/cursos.php';
require 'php/detalhes_cursos.php';

$tecnico_presencial = ($_GET['id'] >= 0 && $_GET['id'] < 10);
$qualificacao = ($_GET['id'] > 9 && $_GET['id'] < 15);
$tecnico_ead = ($_GET['id'] > 14 && $_GET['id'] < 25);
$nr = ($_GET['id'] > 24 && $_GET['id'] < 31);
$qualificacao_ead = ($_GET['id'] > 30 && $_GET['id'] < 34);
$nr_ead = ($_GET['id'] > 33 && $_GET['id'] < 37);
?>
<link rel="stylesheet" href="css/curso.css">
<section id="curso" class="d-flex text-center align-items-center mb-4" style="background-image: url('img/banner.webp');">
    <div class="container">
        <div class="row pt-4">
            <div class="col-md-12">
                <button class="btn btn-lg btn-primary text-light py-2 px-3 fw-bold">
                    <?php
                    if($tecnico_presencial){
                    ?>
                    <?= $cursos[$_GET['id']]." Presencial"?>
                    <?php
                    } elseif($qualificacao){
                    ?>
                    <?= $cursos[$_GET['id']] ?>
                    <?php
                    } elseif($nr || $qualificacao_ead || $nr_ead){
                    ?>
                    <?= $cursos[$_GET['id']-10] ?>
                    <?php
                    } elseif($tecnico_ead){
                    ?>
                    <?= $cursos[$_GET['id']-15]." EAD"?>
                    <?php
                    }
                    ?>
                </button>
            </div>
        </div>
    </div>
</section>
<?php
if($qualificacao_ead || $nr_ead){
?>
<section>
    <div class="container">
        <div class="col-sm-4 mx-auto">
            <div class="card">
                <div class="card-body">
                    <?php
                    if($nr_ead){
                    ?>
                    <h5 class="card-title text-center">R$ <?= $valores_nr[$_GET['id']-34] ?>,00</h5>
                    <?php
                    }
                    ?>
                    <?php
                    if($qualificacao_ead){
                    ?>
                    <h5 class="card-title text-center">R$ <?= $valores_qualificacao[$_GET['id']-31][1] ?>,00</h5>
                    <p class="card-text text-center">Serão <?= $valores_qualificacao[$_GET['id']-31][0] ?> mensalidades nesse valor</p>
                    <?php
                    }
                    ?>
                    <div class="text-center">
                        <button class="btn btn-primary mt-2 fw-bold" data-bs-toggle="modal" data-bs-target="#formModal">Comprar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
}
?>
<section class="mb-5">
    <div class="container">
        <div class="mb-3">
            <?php
            if($tecnico_presencial || $tecnico_ead){
            ?>
            <a href="/#cursos" class="fw-bold btn btn-info"><i class="fa-solid fa-backward me-2"></i>Voltar</a>
            <?php
            } else if($qualificacao){
            ?>
            <a href="/?categoria=qualificacao#cursos" class="fw-bold btn btn-info"><i class="fa-solid fa-backward me-2"></i>Voltar</a>
            <?php
            } else if($nr){
            ?>
            <a href="/?categoria=normas#cursos" class="fw-bold btn btn-info"><i class="fa-solid fa-backward me-2"></i>Voltar</a>
            <?php
            } 
            ?>
        </div>
        <div id="pre-requisito">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Pré-Requisitos
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <?php
                    if($tecnico_presencial || $tecnico_ead){
                    ?>
                    <p>Ter concluído ou estar cursando o último ano do ensino médio.</p>
                    <?php
                    } elseif($qualificacao || $qualificacao_ead){
                    ?>
                    <p>Não tem pré-requisito.</p>
                    <?php
                    } elseif($nr){
                    ?>
                    <p><?= $detalhes_nr[$_GET['id']-25][0] ?></p>
                    <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <div id="carga_horaria" style="<?= ($nr || $nr_ead) ? 'display:none;' : '' ?>">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Carga Horária
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <?php
                    if($tecnico_presencial || $qualificacao){
                    ?>
                    <p><?= $detalhes_cursos[$_GET['id']][1] ?></p>
                    <p>Carga Horária Total: <?= $detalhes_cursos[$_GET['id']][2] ?></p>
                    <?php
                    } elseif($tecnico_ead){
                    ?>
                    <p>
                    De acordo com a resolução Nº 150/2019 do Conselho Estadual de Educação (CEE/MA) os cursos técnicos na modalidade a distância (EAD) possuem suas cargas horárias divididas em AULAS REMOTAS (70% da carga horária) e PRESENCIAS (30% da carga horária). 
                    </p>
                    <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <div id="horario_aula" style="<?= ($nr || $nr_ead) ? 'display:none;' : '' ?>">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Horário de Aula
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <?php
                    if($tecnico_presencial){
                    ?>
                    <ul>
                        <li>
                            <p>Turmas pela manhã de segunda a sexta das 8h30h às 11h30</p>
                        </li>
                        <li>
                            <p>Turmas à noite de segunda a sexta das 19h às 22h</p>
                        </li>
                    </ul>
                    <?php
                    } elseif($_GET['id'] == 10 || $_GET['id'] == 11){
                    ?>
                    <ul>
                        <li>
                            <p>03 (três) aulas por semana das 19h às 22h</p>
                        </li>
                        <li>
                            <p>02 (duas) aulas por semana no caso de divisão de turmas para aulas práticas</p>
                        </li>
                        <li>
                            <p>Os dias da semana para as aulas são estabelecimento pela coordenação do curso</p>
                        </li>
                    </ul>
                    <?php
                    } elseif($_GET['id'] == 12 || $_GET['id'] == 14){
                    ?>
                    <ul>
                        <li>
                            <p>Aos sábados das 8h às 12h</p>
                        </li>
                    </ul>
                    <?php
                    } elseif($_GET['id'] == 13){
                    ?>
                    <ul>
                        <li>
                            <p>02 (três) aulas por semana das 19h às 22h</p>
                        </li>
                        <li>
                            <p>Os dias da semana para as aulas são estabelecimento pela coordenação do curso</p>
                        </li>
                    </ul>
                    <?php
                    } elseif($tecnico_ead){
                    ?>
                    <ul>
                        <li>
                            <p>Nas aulas gravadas o aluno poderá assistir remotamente em qualquer horário do dia</p>
                        </li>
                        <li>
                            <p>Os encontros das aulas presenciais ocorrem quinzenalmente, às sextas das 19h às 22h e sábados das 8h às 12h</p>
                        </li>
                    </ul>
                    <?php
                    } 
                    ?>
                </div>
            </div>
        </div>
        <div id="objetivo_curso">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Objetivo do Curso
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <?php
                    if($tecnico_presencial || $qualificacao){
                    ?>
                    <p><?= $detalhes_cursos[$_GET['id']][0] ?></p>
                    <?php
                    } elseif($tecnico_ead){
                    ?>
                    <p><?= $detalhes_cursos[$_GET['id']-15][0] ?></p>
                    <?php
                    } elseif($nr){
                    ?>
                    <p><?= $detalhes_nr[$_GET['id']-25][1] ?></p>
                    <?php
                    }
                    ?>
                </div>
            </div>
        </div>
        <?php
        if($tecnico_presencial || $qualificacao){
        ?>
        <div id="metodo_ensino">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Metodologia
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <p>Aulas presenciais em salas de aulas expositivas, e práticas em laboratórios especializados.</p>
                </div>
            </div>
        </div>
        <?php
        }
        ?>
        <div id="matriz_curricular">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                <?= ($nr || $nr_ead) ? 'Ementa' : 'Matriz Curricular' ?>
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <div class="table-responsive">
                    <?php 
                    $id = $_GET['id'];
                    include "matriz_curricular/curso{$id}.html";
                    ?>
                    </div>
                    <p><strong><?= $nr ? 'Carga Horária: '.$detalhes_nr[$_GET['id']-25][2] : '' ?></strong></p>
                </div>
            </div>
        </div>
        <div id="documentos" style="<?= ($nr || $nr_ead) ? 'display:none;' : '' ?>">
            <h6>
                <span><i class="fa-solid fa-plus"></i></span>
                Documentos Necessários Para Matrícula
            </h6>
            <div class="card escondido">
                <div class="card-body">
                    <ul>
                        <?php
                        if($tecnico_presencial || $tecnico_ead || $nr){
                        ?>
                        <li>
                            <p>Cópia autenticada do certificado de Ensino Médio</p>
                        </li>
                        <?php
                        }
                        ?>
                        <li>
                            <p>Cópia autenticada da Identidade</p>
                        </li>
                        <li>
                            <p>Cópia autenticada do CPF</p>
                        </li>
                        <li>
                            <p>Cópia de comprovante de residência</p>
                        </li>
                        <li>
                            <p>1 (uma) foto 3 X 4</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Pop up -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="formModalLabel">Criar Conta</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="criar_conta_comprar">
                    <div class="mb-3">
                        <label for="login" class="form-label">Login</label>
                        <input type="text" class="form-control" id="login" name="login" required>
                    </div>
                    <div class="mb-3">
                        <label for="senha" class="form-label">Senha</label>
                        <input type="password" class="form-control" id="senha" name="senha" required>
                    </div>
                    <div class="mb-3">
                        <label for="conf_senha" class="form-label">Confirmar Senha</label>
                        <input type="password" class="form-control" id="conf_senha" required>
                    </div>
                    <div class="mb-3">
                        <label for="nome" class="form-label">Nome</label>
                        <input type="text" class="form-control" id="nome" name="nome" required>
                    </div>
                    <div class="mb-3">
                        <label for="cpf" class="form-label">CPF</label>
                        <input type="text" class="form-control" id="cpf" name="cpf" placeholder="XXX.XXX.XXX-XX" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="contato" class="form-label">Telefone</label>
                        <input type="text" class="form-control" id="contato" name="contato" placeholder="(XX) XXXXX-XXXX" required>
                    </div>
                    <div class="mb-3">
                        <label for="endereco" class="form-label">Endereço</label>
                        <textarea class="form-control" id="endereco" name="endereco" rows="3" required></textarea>
                    </div>
                    <input type="hidden" name="tipo_pagamento" value="boleto">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="js/curso.js"></script>