<link rel="stylesheet" href="css/galeria.css">
<div class="container mt-4 pb-5" id="galeria">
    <div class="row d-flex justify-content-start mt-2">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h4 class="text-center mb-5">Galeria de Fotos e Vídeos</h4>
    <h5 class="mb-3">Curso de Primeiros Socorros</h5>
    <section class="mb-5">
        <div class="row">
            <div class="col-6 col-lg-4 col-xl-3 mb-3">
                <img src="galeria/img1.jpg" class="img-fluid">
            </div>
            <div class="col-6 col-lg-4 col-xl-3 mb-3">
                <img src="galeria/img2.jpg" class="img-fluid">
            </div>
            <div class="col-6 col-lg-4 col-xl-3 mb-3">
                <img src="galeria/img3.jpg" class="img-fluid">
            </div>
            <div class="col-6 col-lg-4 col-xl-3 mb-3">
                <img src="galeria/img4.jpg" class="img-fluid">
            </div>
        </div>
    </section>
</div>