<link rel="stylesheet" href="css/localizacao.css">
<div class="container mt-4" id="localizacao">
    <div class="row d-flex justify-content-start mt-2">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h4 class="mb-4 text-center">
        <i class="fa-solid fa-location-dot mr-2"></i>
        Localização
    </h4>
    <p class="mb-3">Rua Antonio Vieira, 37 - COHAB Anil IV, São Luís - MA, 65051-670</p>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3985.890562180975!2d-44.21825542632363!3d-2.5425474974357902!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7f692204da1eccf%3A0xc1c0ace7db62a5a7!2sNetcom%20Treinamentos%20e%20Solu%C3%A7%C3%B5es%20Tecnol%C3%B3gicas!5e0!3m2!1spt-BR!2sbr!4v1739741563076!5m2!1spt-BR!2sbr" width="100%" height="330px" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>