<link rel="stylesheet" href="css/programacao.css">
<div class="container mt-4" id="programacao">
    <div class="row d-flex justify-content-start">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h4 class="text-center mb-5" id="prog_turmas">Programação das Novas Turmas</h4>
    <div class="row">
        <div class="col-md-6 mb-5">
            <img src="tabelas/tecnico.png" class="tabela img-fluid">
        </div>
        <div class="col-md-6 mb-5">
            <img src="tabelas/tecnico_ead.png" class="tabela img-fluid">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 mb-5">
            <img src="tabelas/qualificacao.png" class="tabela img-fluid">
        </div>
        <div class="col-md-6 mb-5">
            <img src="tabelas/eletroeletronica.png" class="tabela img-fluid">
        </div>
    </div>
    <h6 class="mb-5">
    Obs.: As cargas horárias dos cursos técnicos obedecem a determinação do MEC constante no catálogo nacional de cursos técnicos.
    </h6>
</div>
<script src="js/programacao.js"></script>