<link rel="stylesheet" href="css/programacao.css">
<div class="container mt-4" id="programacao">
    <div class="row d-flex justify-content-start">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h4 class="text-center mb-5" id="prog_turmas">Programação das Novas Turmas</h4>
    <div class="row">
        <div class="col-md-10 offset-md-1 mb-5">
            <img src="tabelas/nr.png" class="tabela img-fluid">
        </div>
    </div>
</div>