<link rel="stylesheet" href="css/sobre_nos.css">
<div class="container mt-4" id="sobre_nos">
    <div class="row d-flex justify-content-start mt-2">
        <div class="col-1">
            <a href="/" class="btn btn-primary">
                <i class="fa-solid fa-backward-fast"></i>
            </a>
        </div>
    </div>
    <h4 class="text-center mb-5">Sobre Nós</h4>
    <h5>Quem Somos</h5>
    <p class="text-justify">
    <span class="me-5"></span>A NETCOM Treinamentos e Soluções Tecnológicas foi fundada em maio de 2004 pelos Engenheiros Eletricistas Maranhenses, Carlos Cesar Bezerra de Carvalho, que trabalhou nas principais empresas de Telecomunicações do Maranhão (Telemar, Vésper e Embratel) e Paulo Henrique Bezerra de Carvalho, que trabalhou no Centro de Lançamento de Alcântara (CLA) e na Telma/Telemar.
    <br><span class="me-5"></span>A NETCOM iniciou suas atividades na cidade de São Luís (MA) com ênfase na capacitação tecnológica de profissionais das áreas da indústria e do mercado de serviços. Atualmente, a Netcom atua também na cidade de Parauapebas (PA).
    <br><span class="me-5"></span>Ao longo desses anos, a NETCOM tornou-se referência em Ensino Tecnológico no Maranhão, devido ao compromisso assumido com seus alunos, através de uma metodologia de ensino diferenciada, investimentos em infraestrutura de laboratórios e, adicionalmente, oferecendo aos seus egressos uma política de colocação no mercado de trabalho.
    <br><span class="me-5"></span>Desde o início de suas atividades, os seus alunos sempre foram bem aceitos pelas empresas maranhenses nas condições de estagiários ou funcionários. Entre os principais parceiros se destacam a VALE, VLI, EQUATORIAL, ALUMAR e AMBEV. 
    </p>
    <h5>Missão</h5>
    <p>
    <span class="me-5"></span>Promover o desenvolvimento econômico e social através da educação tecnológica
    </p>
    <h5>Visão</h5>
    <p>
    <span class="me-5"></span>Tornar-se referência em ensino tecnológico no norte e nordeste do Brasil.
    </p>
    <h5>Valores</h5>
    <ul class="pb-5">
        <li>Honestidade</li>
        <li>Transparência</li>
        <li>Proatividade</li>
        <li>Compromisso Social</li>
        <li>Comprometimento com o Resultado</li>
    </ul>
</div>