<?php
$cursos=[
    'Redes de Computadores',
    'Eletrotécnica',
    'Informática',
    'Eletromecânica',
    'Automação Industrial',
    'Eletrônica',
    'Mecatrônica',
    'Telecomunicações',
    'Mecânica',
    'Eletroeletrônica',
    'Mecânica de Refrigeração',
    'Mecânica Automotiva e Injeção Eletrônica',
    'Mecânica de Motocicletas',
    'Manutenção de Equipamentos Eletrônicos',
    'Instalação de Sistema de Energia Solar',
    'NR 10 - Básico',
    'NR 10 - SEP',
    'NR 10 - Reciclagem',
    'NR-35 – Prevenção de Riscos no Trabalho em Altura',
    'NR-33 - Espaço Confinado Para Vigias e Empregados Autorizados',
    'NR-33 - Espaço Confinado Para Supervisor de Entrada'
];
$img=[
    'tec_rede_comp.jpg',
    'tec_eletrotecnica.jpg',
    'tec_informatica.jpeg',
    'tec_eletromecanica.png',
    'tec_automacao_industrial.png',
    'tec_eletronica.jpeg',
    'tec_mecatronica.png',
    'tec_telecomunicacoes.jpeg',
    'tec_mecanica.png',
    'tec_eletroeletronica.png',
    'mec_refri.jpeg',
    'mec_automotiva.jpeg',
    'mec_moto.png',
    'man_equip_eletronicos.jpeg',
    'inst_energia_solar.jpg',
    'tec_rede_comp.jpg',
    'tec_eletrotecnica.jpg',
    'tec_informatica.jpeg',
    'tec_eletromecanica.png',
    'tec_automacao_industrial.png',
    'tec_eletronica.jpeg',
    'tec_mecatronica.png',
    'tec_telecomunicacoes.jpeg',
    'tec_mecanica.png',
    'tec_eletroeletronica.png',
    'nr10-reciclagem.jpg',
    'nr10-reciclagem.jpg',
    'nr10-reciclagem.jpg',
    'nr-35.jpg',
    'vigias.JPG',
    'supervisor.PNG'
]
?>